---
pagetitle: "Key climate & ocean drivers"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
library(leaflet)
library(magrittr)
```

```{r svg, child = '_key-climate-ocean.Rmd'}
```

`r infographiqR::get_modal_info(info_modal_links_csv = "https://docs.google.com/spreadsheets/d/1yEuI7BT9fJEcGAFNPM0mCq16nFsbn0b-bNirYPU5W8c/gviz/tq?tqx=out:csv&sheet=info_modal_links")`

# Seascape CHECK, JENN THINKS WE SHOULD CUT

```{r}
# get most recent date
d_2 <- onmsR::get_dates(scape)[2]

leaflet::leaflet(
  nms_ply,
  options = leaflet::leafletOptions(
    crs = leaflet::leafletCRS(crsClass = "L.CRS.EPSG4326"))) %>%
  # basemap from GBIF in 4326
  leaflet::addTiles("//tile.gbif.org/4326/omt/{z}/{x}/{y}@1x.png?style=gbif-geyser") %>%
  # sst
  leaflet::addWMSTiles(
    baseUrl = 'https://cwcgom.aoml.noaa.gov/erddap/wms/noaa_aoml_4729_9ee6_ab54/request?',
    layers = "noaa_aoml_4729_9ee6_ab54:CLASS",
    options = leaflet::WMSTileOptions(
      version = "1.3.0", format = "image/png", transparent = T, opacity = 0.7,
      time = format(d_2,"%Y-%m-%dT00:00:00Z")))  %>%
  leaflet::addPolygons() %>% 
  leaflet::addMarkers(lng = ~lon, lat = ~lat, label = ~id, data=site) %>%
  leaflet::addMouseCoordinates() %>%
  leaflet::addLegend(
    position="bottomright",
    title = paste0("CLASS<br>", format(d_2,"%Y-%m-%d")),
    colorNumeric("Spectral", c(1,33), reverse=T), seq(1,33))
```

`r infographiqR::md_caption("Figure Ux.Ocean.Seascape.ERD.map.")`

`r infographiqR::md_caption("Figure Ux.Ocean.Seascape.ERD.map.", get_details = T)`








