##  {.tabset} 

### PISCO: Islands

![**Figure App.F.12.10.** Average density (+/- standard error) of California spiny lobster Panulirus interruptus at 14 sites across four islands in Channel Islands National Marine Sanctuary monitored by the PISCO kelp forest monitoring program from 2003–2016. Lobster abundance is low at San Miguel (blue) and Santa Rosa (purple) islands and appears to be slowly increasing recently at Anacapa (red) and Santa Cruz (orange) islands. Lobster are counted by SCUBA divers swimming along transect lines. Lobster density was averaged across all monitoring sites at each island, including sites located inside and outside of marine reserves and conservation areas, to examine course-scale trends by island. At a finer scale, lobster density is responding differently inside and outside of some marine protected areas (MPAs) in CINMS. A discussion of MPA effects in CINMS is available in MPA Effects. Data source: PISCO; Figure: R. Freedman/NOAA](../img/cinms_cr/App.F.12.10.SpinyLobster_PISCO.jpg)

### NPS: Islands

![**Figure App.F.12.11.** Average density (+/- standard error) of California spiny lobster _Panulirus interruptus_ at Channel Islands National Park kelp forest monitoring sites at the five islands in CINMS. Recent increases in average density of lobster were observed at Anacapa (purple), Santa Cruz (green), and Santa Barbara (orange) islands. Lobster are counted by SCUBA divers. Lobster density was averaged across all monitoring sites at each island, including sites located inside and outside of marine reserves and conservation areas, to examine course-scale trends by island. At a finer scale, lobster density is responding differently inside and outside of some marine protected areas (MPAs) in CINMS. A discussion of MPA effects in CINMS is available in MPA Effects. Figure: Channel Islands National Park.](../img/cinms_cr/App.F.12.11.Panulirus_interruptus_CINP.jpg)