### Contaminants

#### Domoic Acid

![**Figure App.D.7.1.** Domoic acid levels in parts per million (ppm) in commercially-important crustaceans (triangles) and bivalves (circles) collected from the Santa Barbara Channel between 2012 and 2013 are shown on the y-axis for (A) animals collected near the shore of the mainland coast, and (B) animals collected offshore the mainland coast or near the northern Channel Islands. In the cases that are colored red, domoic acid levels measured above the California Department of Public Health and U.S. Food and Drug Administration action limits: 20 ppm for meat and 30 ppm for viscera. Figure: C. Culver/CA Sea Grant, unpublished data](../img/cinms_cr/App.D.7.1_DA levels in crustaceans and bivalves in 2012 and 2013_C. Culver CA Sea Grant copy.jpg)


![Figure App.D.7.3. In May 2015, an unprecedented West Coast-wide harmful algal bloom (HAB) extended from the Gulf of Alaska to southern California. The bloom was composed of Pseudo-nitzschia, a toxigenic diatom that has the ability to produce domoic acid, a potent neurotoxin that can cause amnesic shellfish poisoning (ASP) and threaten human health if affected shellfish are consumed. These satellite images show chlorophyll-a estimates averaged over the periods of March 27–31, 2015 (left panel), and May, 6–8, 2015 (right panel). Data source: Satellite data were obtained from the National Aeronautics and Space Administration Ocean Biology Processing Group (OBPG) using a combination of the MODerate resolution Imaging Spectroradiometer (MODIS) on Aqua and Visible Infrared Imaging Radiometer Suite (VIIRS) chlorophyll products. Data were processed using standard OBPG processing with 4 kilometer imagery. Figure: McCabe et al. 2016](../img/cinms_cr/App.D.7.3_2015 HAB_McCabe et al. 2016.jpg)