### Visitors

![**Figure App.C.4.8.** Annual number of visitors brought to Frenchy’s Cove, Anacapa Island, by the Island Packers Company. At south Frenchy’s Cove and adjacent reefs, Island Packers Company conducts classroom programs for school groups typically during winter and spring months. No records are available for the number of private boaters that went ashore at any of the Channel Islands in the park. Figure: Channel Islands National Park](../img/cinms_cr/App.C.4.8.Visitation_Frenchys.jpg)

![**Figure App.C.4.7. Spatial patterns in coastal recreational activity levels in southern California (all activity types combined). Based on a standing internet panel designed to be demographically representative and surveyed 4,492 individuals in select south coast region counties. Activities at Channel Islands National Marine Sanctuary (CINMS) included: beach-going (SRI), scenic enjoyment (SRI, SCI, Anacapa, SBI), photography (SRI, SCI, Anacapa), birdwatching (SRI, SCI, SBI), and hiking (SRI, SCI). Figure: Chen et al. 2015c](../img/cinms_cr/App.C.4.7_chen_recreation.jpg)