---
output:
html_document:
self_contained: false
lib_dir: "libs"
fig_height: 2
fig_width: 4
params:
element: "crabs"
---

```{r, echo=FALSE, message=F, warning=F}
knitr::opts_chunk$set(echo=F, message=F, warning=F)
library(infographiq)
```

<base target="_parent">
Pacific Fisheries Information Network (PacFIN;
http://pacfin.psmfc.org/), additional calculations: Crab landings (1000's of
metric tons) on the U.S. West Coast. Crab species include Dungeness
(Metacarcinus magister), tanner (Chionoecetes spp.), rock (Cancer spp.) and
unspecified crabs.


```{r out.width='100%'}
tryCatch(
    plot_dygraph_timeseries(
        csv_tv  = "http://oceanview.pfeg.noaa.gov/erddap/tabledap/cciea_AC.csvp?time%2Ccrab_coastwide&time%3E=1980-01-01&time%3C=2014-01-01",
        title   = "Crab Landings (coastwide)",
        y_label = "(1000s metric tons)",
        col_t   = "time (UTC)",
        col_y   = "crab_coastwide (1000s metric tons)"
        #skip_lines
        #group_by  
        #std_err   
        #filter
    ),
    error = function(e) e
)
```
