
```{r, include=F}
knitr::opts_chunk$set(echo=F, message=F, warning=F, error=F)

library(glue)
source(here::here("scripts/calcofi.R"))

```

## {.tabset}

### Map of Regions

### Anchovies

#### CINMS Region

```{r}
grp   <- "Anchovy"
rgn   <- "CINMS"

title <- glue("{grp} - {rgn} Region")
csv   <- glue("https://raw.githubusercontent.com/marinebon/calcofi-analysis/master/data/{grp}_{rgn}.csv")

calcofi_plot(csv = csv, title = title)
```

#### SoCal Shelf Region

```{r}
grp   <- "Anchovy"
rgn   <- "SoCal Shelf"

title <- glue("{grp} - {rgn} Region")
csv   <- glue("https://raw.githubusercontent.com/marinebon/calcofi-analysis/master/data/{grp}_{rgn}.csv")

#download.file(csv, "_tmp.csv")
calcofi_plot(csv = csv, title = title)
```

### Hake

#### CINMS Region

#### SoCal Shelf Region

### Myctophids

#### CINMS Region

```{r}
grp   <- "Myctophids"
rgn   <- "CINMS"

title <- glue("{grp} - {rgn} Region")
csv   <- glue("https://raw.githubusercontent.com/marinebon/calcofi-analysis/master/data/{grp}_{rgn}.csv")

calcofi_plot(csv = csv, title = title)
```

#### SoCal Shelf Region

```{r}
grp   <- "Myctophids"
rgn   <- "SoCal Shelf"

title <- glue("{grp} - {rgn} Region")
csv   <- glue("https://raw.githubusercontent.com/marinebon/calcofi-analysis/master/data/{grp}_{rgn}.csv")

calcofi_plot(csv = csv, title = title)
```

### Rockfish

#### CINMS Region

#### SoCal Shelf Region

### Sanddab

#### CINMS Region

#### SoCal Shelf Region

### Sardine

#### CINMS Region

#### SoCal Shelf Region

