##  {.tabset} 

### PISCO: Sea Stars on Islands

![**Figure App.F.12.7.** Average density (+/- standard error) of giant spined star Pisaster giganteus (top), ochre star P. ochraceus (middle) and sunflower star Pycnopodia helianthoides (bottom) at 14 sites across four islands in Channel Islands National Marine Sanctuary monitored by the PISCO kelp forest monitoring program from 2003–2016. Sea stars are counted by SCUBA divers swimming along transect lines. Sea star density was averaged across all monitoring sites at each island, including sites located inside and outside of marine reserves and conservation areas, to examine course-scale trends by island. Giant, ochre, and sunflower stars suffered severe declines from 2013 to 2014 at all four islands due to sea star wasting syndrome. Data source: PISCO; Figure: R. Freedman/NOAA](../img/cinms_cr/App.F.12.7.seastars_PISCO.jpg)

### NPS: Giant-spined star

![**Figure App.F.12.8a.** Average density (+/- standard error) of the giant-spined star _Pisaster giganteus_ at Channel Islands National Park kelp forest monitoring sites at the five islands in CINMS. Sea stars are counted by SCUBA divers. Sea star density was averaged across all monitoring sites at each island, including sites located inside and outside of marine reserves and conservation areas, to examine course-scale trends by island. Sea star abundance drastically declined at all islands prior to 2014 monitoring and have remained very low through 2016. Figure: Channel Islands National Park.](../img/cinms_cr/App.F.12.8a.Pisaster_giganteus_CINP.jpg)

### NPS: Sunflower star

![**Figure App.F.12.8a.** Average density (+/- standard error) of the sunflower star _Pycnopodia helianthoides_ at Channel Islands National Park kelp forest monitoring sites at the five islands in CINMS. Sea stars are counted by SCUBA divers. Sea star density was averaged across all monitoring sites at each island, including sites located inside and outside of marine reserves and conservation areas, to examine course-scale trends by island. Sea star abundance drastically declined at all islands prior to 2014 monitoring and have remained very low through 2016. Figure: Channel Islands National Park.](../img/cinms_cr/App.F.12.8b.Pycnopodia_helianthoides_CINP.jpg)

### LTER: Sea stars

![**Figure App.F.12.9.** Average density (+/- standard error) of sea stars (_Pisaster_ and _Pycnopodia_ combined) at two island (dark blue) and nine mainland (light blue) kelp forest sites monitored by the Santa Barbara Channel Long-term Ecological Research (SBC LTER) program. Sea star density had drastically declined all sites prior to 2014 monitoring and remained very low through 2015. Data source: SBC LTER; Figure: R. Freedman/NOAA](../img/cinms_cr/App.F.12.9.seastar_LTER.jpg)