library(here)
library(rgdal)
library(raster)
library(rerddap)
library(glue)
library(sf)
library(fs)
library(tidyverse)
library(lubridate)
library(onmsR) # remotes::install_github("noaa-onms/onmsR")

print('Starting SST...')
onmsR::calculate_statistics("cinms", "jplMURSST41mday", "sst", "statistics_sst_cinms.csv")
print('Starting Chlorophyll...')
onmsR::calculate_statistics("cinms", "nesdisVHNSQchlaMonthly", "chlor_a", "statistics_chl_cinms.csv")
print('Starting SST anomaly')
onmsR::calculate_SST_anomaly("cinms")
print ('Ending')
