library(here)
library(rgdal)
library(raster)
library(rerddap)
library(glue)
library(sf)
library(fs)
library(tidyverse)
library(lubridate)
library(nms4r)

print('Starting...')
nms4r::generate_latest_SST("cinms","jplMURSST41mday", "sst", c("mean", "sd"))
print ('Ending')
