library(here)
library(rgdal)
library(raster)
library(rerddap)
library(glue)
library(sf)
library(fs)
library(tidyverse)
library(lubridate)
library(nms4r)
# remotes::install_github("marinebon/nms4r")

print('Starting SST...')
nms4r::calculate_statistics("cinms", "jplMURSST41mday", "sst", "statistics_sst_cinms.csv")
print('Starting Chlorophyll...')
nms4r::calculate_statistics("cinms", "nesdisVHNSQchlaMonthly", "chlor_a", "statistics_chl_cinms.csv")
print ('Ending')
