---
output:
  html_document:
    keep_md: yes
    theme: lumen # darkly # cosmo # https://bootswatch.com
    self_contained: false
    lib_dir: modal_libs
    mathjax: null
    css: [_modal_styles.css, modal_libs/font-awesome-5.3.1/css/all.min.css, modal_libs/font-awesome-5.3.1/css/v4-shims.min.css]
---

```{r, include=F}
knitr::opts_chunk$set(echo=F, message=F, warning=F, error=F)
source(here::here("../cinms/scripts/rocky.R"))
source(here::here("scripts/utility.R"))
```

`r get_modal_info()`

## {.tabset}

### Map of Sites

```{r}
map_nms_sites("cinms")
```

### Golden Rockweed (_Silvetia compressa_) {.active}

```{r}
plot_intertidal_nms(d_csv, "CINMS", "SILCOM", "Golden Rockweed")
```

### Olive Rockweed (_Hesperophycus californicus_)

```{r}
plot_intertidal_nms(d_csv, "CINMS", "HESCAL", "Olive Rockweed")
```

### Turfweed (_Endocladia muricata_)

```{r}
# TODO: inspect Surfgrass in CINMS; n=1100; Error in seq.int(0, 1, length.out = n)
#plot_intertidal_nms(d_csv, "CINMS", "PHYOVR", "Surfgrass"):

plot_intertidal_nms(d_csv, "CINMS", "ENDMUR", "Turfweed")
```









