```{r, include=F}
knitr::opts_chunk$set(echo=F, message=F, warning=F, error=F)
library(infographiqR) # remotes::install_github("marinebon/infographiqR") 
library(onmsR) # remotes::install_github("noaa-onms/onmsR")
```

`r infographiqR::get_modal_info(info_modal_links_csv = "https://docs.google.com/spreadsheets/d/1yEuI7BT9fJEcGAFNPM0mCq16nFsbn0b-bNirYPU5W8c/gviz/tq?tqx=out:csv&sheet=info_modal_links")`

# {.tabset}

## Human Activities

### {.tabset}

#### Fishing {.tabset}

##### Trends: Commercial Landings

`r infographiqR::render_figure("Figure App.C.4.4.", "../img/cinms_cr/App.C.4.4.Leeworthy_landings.jpg")`

##### Recreational 

`r infographiqR::render_figure("Figure App.C.4.2a.", "../img/cinms_cr/App.C.4.2a.CPFV_trips.jpg")`

`r infographiqR::render_figure("Figure App.C.4.2b.", "../img/cinms_cr/App.C.4.2b.CPFV_landings.jpg")`

#### Visitors {.tabset}
##### Map: Location Recreational Activity

`r infographiqR::render_figure("Figure App.C.4.7.", "../img/cinms_cr/App.C.4.7_chen_recreation.jpg")`

##### Trends: Visitors (CHIS)

`r infographiqR::render_figure("Figure App.C.1.4.", "../img/cinms_cr/App.C.1.4.Vistors_CINP.png")`

#### Research
##### Trends: Active Permits

`r infographiqR::render_figure("Figure App.C.4.18a.", "../img/cinms_cr/App.C.4.18a.Projects_Permits.png")`

`r infographiqR::render_figure("Figure App.C.4.18b.", "../img/cinms_cr/App.C.4.18b.CDFW_Permits.png")`

## Human Impacts

#### Noise

##### {.tabset}

###### Listening Stations

`r infographiqR::render_figure("Figure App.C.2.8.", "../img/cinms_cr/App.C.2.8.jpg")`

###### Trends: Sound Levels

`r infographiqR::render_figure("Figure App.C.4.13.", "../img/cinms_cr/App.C.4.13.CINMS_Noise.jpg")`

