---
pagetitle: "Human Activites and Impacts"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=F}
knitr::opts_chunk$set(echo=F, message=F, warning=F, error=F)
library(infographiqR) # remotes::install_github("marinebon/infographiqR") 
library(onmsR) # remotes::install_github("noaa-onms/onmsR")
```

`r infographiqR::get_modal_info(info_modal_links_csv = "https://docs.google.com/spreadsheets/d/1yEuI7BT9fJEcGAFNPM0mCq16nFsbn0b-bNirYPU5W8c/gviz/tq?tqx=out:csv&sheet=info_modal_links")`

# {.tabset}

## <span style="color:Blue">Human Activities</span>

### {.tabset}

#### Fishing {.tabset}

##### Commercial {.tabset}
###### Trends: Commercial Landings

`r infographiqR::render_figure("Figure App.C.4.4.", "../img/cinms_cr/App.C.4.4.Leeworthy_landings.jpg")`

###### Trends: Halibut Fishery

`r infographiqR::render_figure("Figure App.C.4.5a.", "../img/cinms_cr/App.C.4.5a.Halibut_landings_CDFW.jpg")`

`r infographiqR::render_figure("Figure App.C.4.5b.", "../img/cinms_cr/App.C.4.5b.CDFW_halibut_vessels.jpg")`

###### Trends: Rock Crab Fishery

`r infographiqR::render_figure("Figure App.C.4.6a.", "../img/cinms_cr/App.C.4.6a.crab_landings_CDFW.jpg")`

`r infographiqR::render_figure("Figure App.C.4.6b.", "../img/cinms_cr/App.C.4.6b.crab_fishers_CDFW.jpg")`

###### Trends: By Gear Type

`r infographiqR::render_figure("Figure App.C.3.2.", "../img/cinms_cr/App.C.3.2_CINMSLandings.jpg")`

###### Map: Trawling and Deep Sea Corals

`r infographiqR::render_figure("Figure App.C.3.3.", "../img/cinms_cr/App.C.3.3_SWFSC_Trawls2007-2011_HBCoralsRS.jpg")`

###### Map: Fixed Gear and Deep Sea Corals

`r infographiqR::render_figure("Figure App.C.3.4.", "../img/cinms_cr/App.C.3.4_SWFSC_Fixed2007-2011_Gorgonians.jpg")`

###### Map: Trawl & Fixed Gear with MPAs 

`r infographiqR::render_figure("Figure App.C.3.5.", "../img/cinms_cr/App.C.3.5_SoCalDeepBotFishingMPAs_Etnoyer.jpg")`

##### Recreational {.active}

`r infographiqR::render_figure("Figure App.C.4.2a.", "../img/cinms_cr/App.C.4.2a.CPFV_trips.jpg")`

`r infographiqR::render_figure("Figure App.C.4.2b.", "../img/cinms_cr/App.C.4.2b.CPFV_landings.jpg")`

#### Oil & Gas {.tabset}

##### Trends: Offshore Oil and Gas Activity 

`r infographiqR::render_figure("Figure App.C.4.17.", "../img/cinms_cr/App.C.4.17.Oil_gas_activity_CCIEA.png")`

##### Oil & Gas Maps {.tabset}

###### Offshore Oil Platforms

`r infographiqR::render_figure("Figure App.C.2.1.", "../img/cinms_cr/App.C.2.1 Oil platforms_Mari Cajandig.jpg")`

###### 2015 Refugio Oil Spill

`r infographiqR::render_figure("Figure App.C.2.3.", "../img/cinms_cr/App.C.2.3 Refugio Spill_Mari Cajandig.jpg")`

`r infographiqR::render_figure("Figure App.C.2.4.", "../img/cinms_cr/App.C.2.4.jpg")`

`r infographiqR::render_figure("Figure App.C.2.5.", "../img/cinms_cr/App.C.2.5.jpg")`

#### Vessel Traffic 

##### {.tabset}

###### Map: Vessel Traffic Patterns

`r infographiqR::render_figure("Figure App.C.4.12.", "../img/cinms_cr/App.C.4.12.MSWGSS_2016.jpg")`

#### Visitors

##### {.tabset}

###### Trends: Visitors at Frenchy's Cove

`r infographiqR::render_figure("Figure App.C.4.8.", "../img/cinms_cr/App.C.4.8.Visitation_Frenchys.jpg")`

###### Map: Location Recreational Activity

`r infographiqR::render_figure("Figure App.C.4.7.", "../img/cinms_cr/App.C.4.7_chen_recreation.jpg")`

###### Trends: Visitors (CHIS)

`r infographiqR::render_figure("Figure App.C.1.4.", "../img/cinms_cr/App.C.1.4.Vistors_CINP.png")`

#### Research
###### Trends: Active Permits

`r infographiqR::render_figure("Figure App.C.4.18a.", "../img/cinms_cr/App.C.4.18a.Projects_Permits.png")`

`r infographiqR::render_figure("Figure App.C.4.18b.", "../img/cinms_cr/App.C.4.18b.CDFW_Permits.png")`

## <span style="color:Red">Human Impacts</span>


### {.tabset}

#### Contaminants {.tabset}

##### Benthic Response Index {.tabset}
###### Trends: Condition by region

`r infographiqR::render_figure("Figure App.E.11.10.", "../img/cinms_cr/App.E.11.10.jpg")`

###### Map: 2013 Trends at sites

`r infographiqR::render_figure("Figure App.E.11.9.", "../img/cinms_cr/App.E.11.9.jpg")`

###### Map: 2013 Conditions at sites

`r infographiqR::render_figure("Figure App.E.11.11.", "../img/cinms_cr/App.E.11.11.jpg")`

##### Contaminants in Sediments

###### Map: 2008 DDT 

`r infographiqR::render_figure("Figure App.E.11.12.", "../img/cinms_cr/App.E.11.12.jpg")`

###### Map: 2008 Copper

`r infographiqR::render_figure("Figure App.E.11.13.", "../img/cinms_cr/App.E.11.13.jpg")`

###### Map: 2008 Silver

`r infographiqR::render_figure("Figure App.E.11.14.", "../img/cinms_cr/App.E.11.14.jpg")`

###### Map: 2008 PBDEs

`r infographiqR::render_figure("Figure App.E.11.15.", "../img/cinms_cr/App.E.11.15.jpg")`

###### Map: 2008 Pyrethroids

`r infographiqR::render_figure("Figure App.E.11.16.", "../img/cinms_cr/App.E.11.16.jpg")`

###### Trends: Exposure levels by region

`r infographiqR::render_figure("Figure App.E.11.17.", "../img/cinms_cr/App.E.11.17.jpg")`

##### Contaminants in Mussels

###### Trends: Arsenic

`r infographiqR::render_figure("Figure App.E.11.2.", "../img/cinms_cr/App.E.11.2.jpg")`

###### Trends: Iron

`r infographiqR::render_figure("Figure App.E.11.3.", "../img/cinms_cr/App.E.11.3.jpg")`

###### Trends: Silver

`r infographiqR::render_figure("Figure App.E.11.4.", "../img/cinms_cr/App.E.11.4.jpg")`

###### Trends: Heavy metals

`r infographiqR::render_figure("Figure App.E.11.5.", "../img/cinms_cr/App.E.11.5.jpg")`

###### Trends: PAHs

`r infographiqR::render_figure("Figure App.E.11.6.", "../img/cinms_cr/App.E.11.6.jpg")`

#### Marine Debris

##### {.tabset}

###### Trends: Southern California Beaches 

`r infographiqR::render_figure("Figure App.C.4.14.", "../img/cinms_cr/App.C.4.14.Marine debris_CCIEA.jpg")`

###### Map: debris in CalCOFI trawls (historical)

`r infographiqR::render_figure("Figure App.C.4.15.", "../img/cinms_cr/App.C.4.15.Gilfillan_graph.png")`

###### Trends: debris in CalCOFI trawls (historical)

`r infographiqR::render_figure("Figure App.C.4.16.", "../img/cinms_cr/App.C.4.16.Gilfillan_map.png")`


#### Vessel Groundings


##### Map: Vessel Groundings

`r infographiqR::render_figure("Figure App.C.3.1.", "../img/cinms_cr/App.C.3.1_VesselGroundingsMap.jpg")`


#### Noise

##### {.tabset}

###### Listening Stations

`r infographiqR::render_figure("Figure App.C.2.8.", "../img/cinms_cr/App.C.2.8.jpg")`

###### Trends: Sound Levels

`r infographiqR::render_figure("Figure App.C.4.13.", "../img/cinms_cr/App.C.4.13.CINMS_Noise.jpg")`

#### Seabird disturbance

##### Comparison: By Region

`r infographiqR::render_figure("Figure App.C.4.9.", "../img/cinms_cr/App.C.4.9.Seabird_disturbance_rates_Robinette.jpg")`

#### Trend: oiled beachcast seabirds

`r infographiqR::render_figure("BeachCombers_seabird_deposition_oiling", "../img/cinms_cr/BeachCombers_seabird_deposition_oiling.png")`

#### Whale entanglement {.tabset}

##### Trends: By Species

`r infographiqR::render_figure("Figure App.C.4.10b.", "../img/cinms_cr/App.C.4.10b.Whale_entanglements.png")`

##### Map: Whale Overlap with Fishing {.tabset}

###### Blue

`r infographiqR::render_figure("Figure App.C.4.11a.", "../img/cinms_cr/App.C.4.11a.blue_risk.jpg")`

###### Fin

`r infographiqR::render_figure("Figure App.C.4.11b.", "../img/cinms_cr/App.C.4.11b.fin_risk.jpg")`

###### Humpback

`r infographiqR::render_figure("Figure App.C.4.11c.", "../img/cinms_cr/App.C.4.11c.humpback_risk.jpg")`
