```{r, include=F}
knitr::opts_chunk$set(echo=F, message=F, warning=F, error=F)
library(infographiqR) # remotes::install_github("marinebon/infographiqR") 
library(onmsR) # remotes::install_github("noaa-onms/onmsR")
```

`r infographiqR::get_modal_info(info_modal_links_csv = "https://docs.google.com/spreadsheets/d/1yEuI7BT9fJEcGAFNPM0mCq16nFsbn0b-bNirYPU5W8c/gviz/tq?tqx=out:csv&sheet=info_modal_links")`

# {.tabset}

## Human Activities

### {.tabset}

#### Oil & Gas {.tabset}

##### Trends: Offshore Oil and Gas Activity 

`r infographiqR::render_figure("Figure App.C.4.17.", "../img/cinms_cr/App.C.4.17.Oil_gas_activity_CCIEA.png")`

##### Oil & Gas Maps {.tabset}

###### Offshore Oil Platforms

`r infographiqR::render_figure("Figure App.C.2.1.", "../img/cinms_cr/App.C.2.1 Oil platforms_Mari Cajandig.jpg")`

###### 2015 Refugio Oil Spill

`r infographiqR::render_figure("Figure App.C.2.3.", "../img/cinms_cr/App.C.2.3 Refugio Spill_Mari Cajandig.jpg")`

`r infographiqR::render_figure("Figure App.C.2.4.", "../img/cinms_cr/App.C.2.4.jpg")`

`r infographiqR::render_figure("Figure App.C.2.5.", "../img/cinms_cr/App.C.2.5.jpg")`

#### Visitors

##### {.tabset}

###### Trends: Visitors at Frenchy's Cove

`r infographiqR::render_figure("Figure App.C.4.8.", "../img/cinms_cr/App.C.4.8.Visitation_Frenchys.jpg")`

###### Map: Location Recreational Activity

`r infographiqR::render_figure("Figure App.C.4.7.", "../img/cinms_cr/App.C.4.7_chen_recreation.jpg")`

###### Trends: Visitors (CHIS)

`r infographiqR::render_figure("Figure App.C.1.4.", "../img/cinms_cr/App.C.1.4.Vistors_CINP.png")`

## Human Impacts

### {.tabset}

#### Marine Debris

##### {.tabset}

###### Trends: Southern California Beaches 

`r infographiqR::render_figure("Figure App.C.4.14.", "../img/cinms_cr/App.C.4.14.Marine debris_CCIEA.jpg")`


#### Vessel Groundings

##### {.tabset}

###### Map: Vessel Groundings

`r infographiqR::render_figure("Figure App.C.3.1.", "../img/cinms_cr/App.C.3.1_VesselGroundingsMap.jpg")`



#### Seabird disturbance

##### Comparison: By Region

`r infographiqR::render_figure("Figure App.C.4.9.", "../img/cinms_cr/App.C.4.9.Seabird_disturbance_rates_Robinette.jpg")`

#### Trend: oiled beachcast seabirds

`r infographiqR::render_figure("BeachCombers_seabird_deposition_oiling", "../img/cinms_cr/BeachCombers_seabird_deposition_oiling.png")`
