
```{r, include=F}
knitr::opts_chunk$set(echo=F, message=F, warning=F, error=F)
```

```{r svg, child = '_key-climate-ocean.Rmd'}
```

# {.tabset}
## Temperature {.tabset}
### Map: Satellite-based SST (CoastWatch)

```{r}
# get most recent date
date_end <- get_dates(sst)[2]

leaflet(
  nms_ply,
  options = leafletOptions(
    crs = leafletCRS(crsClass = "L.CRS.EPSG4326"))) %>%
  # basemap from GBIF in 4326
  addTiles("//tile.gbif.org/4326/omt/{z}/{x}/{y}@1x.png?style=gbif-geyser") %>%
  # sst
  addWMSTiles(
    baseUrl = 'https://coastwatch.pfeg.noaa.gov/erddap/wms/jplMURSST41mday/request?',
    layers = "jplMURSST41mday:sst",
    options = WMSTileOptions(
      version = "1.3.0", format = "image/png", transparent = T, opacity = 0.7,
      time = format(date_end,"%Y-%m-%dT00:00:00Z")))  %>%
  addPolygons() %>% 
  addMouseCoordinates() %>%
  addLegend(
    position="bottomright",
    title = paste0("SST (°C)<br>", format(date_end,"%Y-%m-%d")),
    colorNumeric("Spectral", c(0,32), reverse=T), seq(0,32))
```

`r md_caption("Figure Ux.Ocean.SST.ERD.map.")`

`r md_caption("Figure Ux.Ocean.SST.ERD.map.", get_details = T)`



### Trend: Satellite-based SST (CoastWatch)

```{r}
# Note: I wrote a simple new function to plot the new SST time series, since I couldn't figure out
# how the functions get_timeseries or plot_timeseries worked (since I couldn't figure them out, I couldn't
# modify them). The original code is kept below, but commented out

# csv  <- here(glue("data/oceano/sst_{nms}.csv"))
# url  <- glue("https://github.com/marinebon/{nms}/raw/master/data/oceano/{basename(csv)}")
# html <- a(basename(csv), href=url, target='_blank')
# d   <- get_timeseries(sst, lon=site$lon, lat=site$lat, csv=csv, field="sst")
# plot_timeseries(d, title="SST", color="red")

csv_SST <-here(glue("data/oceano/statistics_sst_{nms}.csv"))
url_SST  <- glue("https://github.com/marinebon/{nms}/raw/master/data/oceano/{basename(csv_SST)}")
html_SST <- a(basename(csv_SST), href=url_SST, target='_blank')
nms4r::plot_metric_timeseries(csv_SST, "sst")
```

`r md_caption("Figure Ux.Ocean.SST.ERD.timeseries.")`

`r md_caption("Figure Ux.Ocean.SST.ERD.timeseries.", get_details = T)`

Download timeseries data for sanctuary: `r html_SST`

