---
title: '`r params$title`'
output:
  html_document:
    self_contained: false
    lib_dir: "libs"
params:
  title: "CINMS Ecosystems"
  csv: "/Users/bbest/github/cinms/docs/svg-links.csv"
  svg: "svg/cinms_overview.svg"
  #title: "pelagic"
  #csv: "/Users/bbest/github/cinms/docs/svg-links.csv"
  #svg: "svg/cinms_pelagic.svg"
  #title: "rocky-shore"
  #csv: "svg-links.csv"
  #svg: "svg/cinms_rocky-shore.svg"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F)

#file.exists("svg/pelagic.svg")
```

<div class="form-check">
  <input class="form-check-input" type="checkbox" value="" id="ckbox_questions" data-toggle="toggle"> <!--onclick="hideSVG('SVGid')"-->
  <label class="form-check-label" for="ckbox_questions">
  questions
  </label>
</div>

```{r}
library(tidyverse)
library(glue)
#devtools::install_github("marinebon/infographiq")
devtools::load_all("~/github/infographiq")
#library(infographiq) 
stopifnot(file.exists(params$csv))

message(glue("csv: {params$csv}"))
message(glue("svg: {params$svg}"))
# params <- list(
#   csv = "/Users/bbest/github/cinms/docs/svg-links.csv",
#   svg = "svg/cinms_overview.svg")

svg <- params$svg
d <- read_csv(params$csv) %>% 
  #View()
  filter(svg == !!svg) # %>% 
  #View()

message(glue("nrow(d): {nrow(d)}"))

info_svg(d, svg)
```